name: Test Release

on:
  pull_request:
    branches:
      - masterß
  workflow_call:

jobs:
    test:
        runs-on: large-spot
        steps: 
            - uses: actions/checkout@v4

            - name: Set up Python 3.9
              uses: actions/setup-python@v5
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
                python -m pip install pytest

            - name: Run tests
              run: python -m pytest test/model_unit_test.py
